//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentMngProject_Orgn.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentMngDBEntities : DbContext
    {
        public StudentMngDBEntities()
            : base("name=StudentMngDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch> batch { get; set; }
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<registration> registration { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
